### ISSUE TITLE
Cancel orders - eth value balance doesnt update

### ISSUE THREAD

**Issue by Chwy5** [AugurProject/augur-walkthrough#30]
I was cancelling all (33) open orders in a cat 6 resolved market and i keep getting this can't update warning 35 x's....but the weird thing is my Eth Balance did not update and i have etherscan confirms for all 33 cancels
And got this message in the consol....see attached screenshot

![11-30-35](https://user-images.githubusercontent.com/41301809/49307403-14c37300-f4a3-11e8-8b33-66840f73892f.jpg)

**Comment by adrake33** [comment]
Issue moved to [AugurProject/augur-app #414](https://github.com/AugurProject/augur-app/issues/414) via [**ZenHub**](https://www.zenhub.com/)
